DROP TABLE ACCOUNT IF EXISTS;

CREATE TABLE ACCOUNT (
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR(50),
  BALANCE INTEGER ,
  ACCOUNT_NUMBER INTEGER
);

INSERT INTO ACCOUNT(ID,NAME,BALANCE,ACCOUNT_NUMBER) values(1,'kiran',10000,1001);

INSERT INTO ACCOUNT(ID,NAME,BALANCE,ACCOUNT_NUMBER) values(2,'rohit',5000,2001);
